### ISSUE TITLE
Separating out EHTImage stuff into a separate package

### ISSUE THREAD

**Issue by ptiede** [ptiede/VIDA.jl#28]
I would really like to separate out the EHTImage stuff from VIDA.
 - This would allow me to better interface with eht-imaging using PyCall
 - EHTImage is really separate from VIDA! VIDA should just be filters and convenience functions...

**Comment by KajWiik** [comment]
Hi! Have you seen my https://github.com/KajWiik/EHTIM.jl

It is really a very thin wrapper, pycall seems to be working very well. I am currently working on UVFITSIDI.jl that would read (and later write) both UVFITS and FITS-IDI format files. It uses FITSIO.jl and is otherwise pure Julia. Good to see other Julia users in the EHTC!

**Comment by ptiede** [comment]
I hadn't seen that! That's fantastic that you have already started creating a package for that. I'll take a look at the packages.

**Comment by ptiede** [comment]
@KajWiik would you like to collaborate on making the eht-imaging interface more complete? I have another project I am working on that would do model fitting in pure Julia but I don't have a good interface with eht-imaging or reading in uvfits files.
